name: Release APK from Tag
on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      PUB_CACHE: .pub-cache
      GRADLE_USER_HOME: $GITHUB_WORKSPACE/.gradle
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.5'
          channel: stable
      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            .pub-cache
            .dart_tool
            .flutter-plugins
            .flutter-plugins-dependencies
            android/.gradle
            build
          key: ${{ runner.os }}-build-caches
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/apk/release
